import json
import os
import asyncio
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from agents.prompts import SYSTEM_PROMPT


@dataclass(frozen=True)
class LyzrConfig:
    enabled: bool
    api_key_configured: bool
    mode: str
    reason: str


def get_lyzr_config() -> LyzrConfig:
    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parents[1] / ".env")
    key_present = bool(os.getenv("LYZR_API_KEY"))
    environment = os.getenv("CARBON_AUDIT_ENV", "development").lower()
    if environment in {"test", "testing"}:
        return LyzrConfig(False, key_present, "LOCAL_DETERMINISTIC_FALLBACK", "Test environment disables Lyzr calls; key not configured for live execution.")
    if key_present:
        return LyzrConfig(True, True, "LYZR_LIVE", "Lyzr API key configured.")
    return LyzrConfig(False, False, "LOCAL_DETERMINISTIC_FALLBACK", "LYZR_API_KEY is not configured; Lyzr calls are disabled.")


def _lookup_factor_tool(activity: str, scope: str, unit: str, region: str | None = None, year: int | None = None) -> dict[str, Any]:
    from tools.factor_lookup import lookup_factor

    return lookup_factor(activity, scope, unit, region, year).model_dump()


def _calculate_verified_tool(quantity: float, activity: str, scope: str, unit: str, region: str | None = None, year: int | None = None) -> dict[str, Any]:
    from tools.calculator import calculate_emissions
    from tools.factor_lookup import lookup_factor

    factor = lookup_factor(activity, scope, unit, region, year)
    if factor.status != "VERIFIED":
        return {"status": factor.status, "reason": factor.reason, "factor": None, "emissions": None}
    return {"status": "VERIFIED", "factor": factor.model_dump(), "emissions": calculate_emissions(quantity, factor.factor or 0)}


def _validate_context_tool(activity: str, scope: str, unit: str, region: str | None = None) -> dict[str, Any]:
    from tools.classification import classify_activity
    from tools.unit_conversion import normalize_unit

    classification = classify_activity(activity)
    if classification.scope != scope:
        return {"status": "NEEDS_REVIEW", "reason": "Requested scope does not match conservative classification."}
    return {"status": "CONTEXT_VALID", "confidence": classification.confidence, "unit_check": normalize_unit(1, unit, unit)[0]}


def _audit_evidence_tool(record_id: str) -> dict[str, Any]:
    return {"status": "REQUIRES_RUNTIME_RECORD", "record_id": record_id, "reason": "Audit evidence is generated by the deterministic pipeline."}


class LyzrService:
    """One real Lyzr agent with deterministic local tools and no numeric authority."""

    def __init__(self) -> None:
        self.config = get_lyzr_config()
        self._agent = None

    @property
    def available(self) -> bool:
        return self.config.enabled

    def _create_agent(self):
        if self._agent is not None:
            return self._agent
        if not self.available:
            return None
        try:
            from lyzr import Studio

            studio = Studio()
            self._agent = asyncio.run(studio.acreate_agent(
                name="CarbonAudit ESG Compliance Copilot",
                provider=os.getenv("LYZR_PROVIDER", "gpt-4o-mini"),
                role="ESG compliance reasoning orchestrator",
                goal="Classify compact activity records, identify missing context, flag unsupported sustainability claims, and explain deterministic results.",
                instructions=SYSTEM_PROMPT,
            ))
            for tool in (_lookup_factor_tool, _calculate_verified_tool, _validate_context_tool, _audit_evidence_tool):
                self._agent.add_tool(tool)
            return self._agent
        except ImportError as error:
            raise RuntimeError("lyzr-adk is not installed; install backend requirements.") from error

    async def _reason_async(self, records: list[dict[str, Any]], claims: list[str]) -> dict[str, Any]:
        from lyzr import Studio

        studio = Studio()
        agent = await studio.acreate_agent(
            name="CarbonAudit ESG Compliance Copilot",
            provider=os.getenv("LYZR_PROVIDER", "gpt-4o-mini"),
            role="ESG compliance reasoning orchestrator",
            goal="Classify compact activity records, identify missing context, flag unsupported sustainability claims, and explain deterministic results.",
            instructions=SYSTEM_PROMPT,
        )
        for tool in (_lookup_factor_tool, _calculate_verified_tool, _validate_context_tool, _audit_evidence_tool):
            agent.add_tool(tool)
        compact_input = {"records": [{"record_id": r.get("record_id"), "activity": r.get("activity"), "unit": r.get("unit"), "region": r.get("region"), "year": r.get("year")} for r in records], "claims": claims}
        response = await agent.arun(json.dumps(compact_input, separators=(",", ":")))
        raw = getattr(response, "response", response)
        if isinstance(raw, dict):
            result = raw
        else:
            text = str(raw)
            try:
                result = json.loads(text)
            except json.JSONDecodeError:
                result = {"classifications": [], "claim_flags": [], "narrative": text}
        result["mode"] = "LYZR_LIVE"
        result["response_type"] = type(response).__name__
        return result

    def reason(self, records: list[dict[str, Any]], claims: list[str]) -> dict[str, Any]:
        if not self.available:
            return {"mode": self.config.mode, "reason": self.config.reason, "classifications": [], "claim_flags": [], "narrative": "Deterministic local mode; no Lyzr reasoning was executed."}
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self._reason_async(records, claims))
        raise RuntimeError("Live Lyzr reasoning requires a synchronous worker context.")


_service: LyzrService | None = None


def get_lyzr_service() -> LyzrService:
    global _service
    current_mode = get_lyzr_config().mode
    if _service is None or _service.config.mode != current_mode:
        _service = LyzrService()
    return _service